name: Test cdxgen python

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'repo to clone'
        required: true
        type: string
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get cdxgen
        run: |
          git clone https://github.com/CycloneDX/cdxgen.git
          cd cdxgen
          git checkout feature/deno-docker
          npm pack
          npm install cyclonedx-cdxgen-9.1.0.tgz -g
      
      - name: Test sample repo
        run: |
          git clone ${{ inputs.repo }} testrepo
          cd testrepo
          mkdir upload
          cdxgen -p -t python -o upload/novenvbom.json
      
      - name: Test sample repo within venv
        run: |
          cd testrepo
          python -m venv ./venv
          cd venv/bin
          source activate
          cd ../..
          cdxgen -p -t python -o /upload/venvnopkgbom.json
          pip install -r requirements.txt
          pip freeze >> upload/pipfreeze.txt
          cdxgen -p -t python -o upload/venvpkgbom.json
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: |
            '/testrepo/upload/*'
          
      
      
