# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      repo:
        description: 'repo to clone'
        required: true
        type: string
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get cdxgen
        run: |
          git clone https://github.com/CycloneDX/cdxgen
          git checkout feature/deno-docker
          npm install -g
      
      - name: Test sample repo
        run: |
          git clone ${{ inputs.repo }} testrepo
          cd testrepo
          cdxgen -p -t python
      
      - name: Test sample repo within venv
        run: |
          python -m venv ./venv
          ./venv/bin/activate
          cdxgen -p -t python
          pip install .
          pip freeze
          cdxgen -p -t python
          
      
      
