name: blint

on:
  workflow_dispatch:

jobs:
  blint:
    runs-on: ubuntu-latest

    steps:
      - run: git clone https://github.com/juice-shop/juicy-malware.git
      - name: Run blint
        uses: cerrussell/blint-action@main
        env:
          SCAN_DEBUG_MODE: debug
        with:
          src: juicy-malware
