name: blint

on:
  workflow_dispatch:

jobs:
  blint:
    runs-on: ubuntu-latest

    steps:
      - run: git clone https://github.com/juice-shop/juicy-malware.git
      - run: ls
      - name: Run blint
        uses: cerrussell/blint-action@main
        with:
          src: |
            juicy-malware
            workspace
