name: blint

on:
  workflow_dispatch:

jobs:
  blint:
    runs-on: ubuntu-latest

    steps:
      - run: git clone https://github.com/juice-shop/juicy-malware.git
      - name: Run blint
        env: |
          SCAN_DEBUG_MODE:debug
        uses: cerrussell/blint-action@main
        with:
          src: juicy-malware
