name: Test evinse

on:
  workflow_dispatch:
    inputs:
      ptype:
        description: 'project type'
        required: false
        default: 'python'
        type: string
      with-evinse:
        description: 'run evinse as well as cdxgen'
        required: false
        default: false
        type: boolean
run-name: ${{ inputs.ptype }}-repos
        
jobs: 
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
         python-version: "3.10"
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: "temurin"
          java-version: "19"
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18
   
      - name: Get cdxgen and poetry
        run: |
          pipx install poetry
          # git clone https://github.com/CycloneDX/cdxgen.git
          # cd cdxgen
          # git checkout feature/evinse-python
          npm install -g @cyclonedx/cdxgen
      - uses: actions/checkout@v3
      - name: Get sample repos and run cdxgen/evinse
        shell: pwsh
        env:
          CDXGEN_DEBUG_MODE: debug
          MATRIX_OS: ${{ matrix.os }}
          WITH_EVINSE: ${{ inputs.with-evinse }}
        run: .\${{ inputs.ptype }}.ps1
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            artifacts-${{ matrix.os }}/**/*.json
