name: depscan tests

on:
  workflow_dispatch:
jobs:
  ubuntu_version_tests2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: checkout depscan
        uses: actions/checkout@v4
        with:
          repository: OWASP-dep-scan/dep-scan
          ref: release/6.x
          path: depscan
      - name: install depscan
        run: |
          cd depscan
          python3 -m pip install --upgrade pip
          python3 -m pip install .
          python3 -m pip install -r contrib/requirements.txt
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20
      - name: cdxgen, sdkman installs
        run: |
         npm install -g @cyclonedx/cdxgen
         curl -s "https://get.sdkman.io" | bash
         source "/home/runner/.sdkman/bin/sdkman-init.sh"
      - name: run script
        env:
          SDKMAN_DIR: /home/runner/.sdkman
          CDXGEN_DEBUG_MODE: debug
        run: |
          bash /home/runner/work/cdxgen-testing/cdxgen-testing/depscan_script.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: |
            /home/runner/work/artifacts
