name: Test evinse

on:
  workflow_dispatch:

        
jobs: 
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
         python-version: "3.10"
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: "temurin"
          java-version: "19"
   
      - name: Get cdxgen
        run: |
          git clone https://github.com/CycloneDX/cdxgen.git
          cd cdxgen
          git checkout feature/evinse-python
          npm pack
          npm install -g cyclonedx-cdxgen-9.9.1.tgz
      - name: Get sample repos
        run: |
          git clone https://github.com/puppeteer/puppeteer.git puppeteer
          git clone https://github.com/Tautulli/Tautulli.git tautulli
          git clone https://github.com/keras-team/keras.git keras
      - name: Test sample repos
        env:
          CDXGEN_DEBUG_MODE: debug
        run: |
          mkdir artifacts artifacts/puppeteer artifacts/tautulli artifacts/keras
          cdxgen -p -t python --deep -o artifacts/puppeteer/puppeteer-bom-${{ matrix.os }}.json puppeteer
          evinse -p -i artifacts/puppeteer/puppeteer-bom-${{ matrix.os }}.json -o artifacts/puppeteer/puppeteer-evinse-${{ matrix.os }}.json -l python --with-reachables puppeteer
          cdxgen -p -t python --deep -o artifacts/tautulli/tautulli-bom-${{ matrix.os }}.json tautulli
          evinse -p -i artifacts/tautulli/tautulli-bom-${{ matrix.os }}.json -o artifacts/tautulli/tautulli-evinse-${{ matrix.os }}.json -l python --with-reachables tautulli
          cdxgen -p -t python --deep -o artifacts/keras/keras-bom-${{ matrix.os }}.json keras
          evinse -p -i artifacts/keras/keras-bom-${{ matrix.os }}.json -o artifacts/keras/keras-evinse-${{ matrix.os }}.json -l python --with-reachables keras
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            artifacts
